version: '2'
services:
  chartmuseum:
    image: bitnami/chartmuseum:0
    ports:
      - '8080:8080'
    volumes:
      - chartmuseum_data:/bitnami/data
volumes:
  chartmuseum_data:
    driver: local
