## This is test deployment for Kubernetes platforms.
## This is _not_ intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-chartmuseum
  name: test-chartmuseum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-chartmuseum
  template:
    metadata:
      labels:
        app: test-chartmuseum
    spec:
      containers:
      - image: bitnami/chartmuseum
        name: chartmuseum
